swagger: "2.0"
info:
  description: "The API definition for Contacts CRUD API"
  version: "1.0.0"
  title: "Swagger Contacts CRUD"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.io"
basePath: "/api/v1"
tags:
  - name: "contacts"
    description: "Everything about contacts"
schemes:
  - "http"
paths:
  /contacts:
    get:
      tags:
        - "contacts"
      summary: "Retrive the list of existen contacts"
      operationId: "retrieveContacts"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        "200":
          description: "The list of the existen contacts"
    post:
      tags:
        - "contacts"
      summary: "Register a new contact"
      operationId: "registerContact"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Contact object that needs to be registered"
          required: true
          schema:
            $ref: "#/definitions/ContactAttributes"
      responses:
        "200":
          description: "Created contact"
        "405":
          description: "Invalid input"
  /contacts/{id}:
    get:
      tags:
        - "contacts"
      summary: "Find contact by ID"
      description: "Returns a single contact"
      operationId: "getContactById"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of contact to return"
          required: true
          type: "integer"
          format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Contact"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Contact not found"
    post:
      tags:
        - "contacts"
      summary: "Updates a contact with provided form data"
      operationId: "updateContactWithForm"
      consumes:
        - "application/x-www-form-urlencoded"
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "Contact id to delete"
          required: true
          type: "integer"
          format: "int64"
        - in: "body"
          name: "body"
          description: "Contact object that needs to be registered"
          required: true
          schema:
            $ref: "#/definitions/ContactAttributes"
      responses:
        "201":
          description: "Contact updated"
    delete:
      tags:
        - "contacts"
      summary: "Deletes a contact"
      operationId: "deleteContact"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "Contact id to delete"
          required: true
          type: "integer"
          format: "int64"
      responses:
        "400":
          description: "Invalid ID supplied"
        "201":
          description: "Contact deleted"
definitions:
  Contact:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      attributes:
        $ref: "#/definitions/ContactAttributes"
    xml:
      name: "Tag"
  ContactAttributes:
    type: "object"
    properties:
      firstName:
        type: "string"
      lastName:
        type: "string"
      email:
        type: "string"
      phoneNumber:
        type: "string"
